// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartComplaint.Data;

#nullable disable

namespace SmartComplaint.Migrations
{
    [DbContext(typeof(ComplaintContext))]
    [Migration("20251118093457_AddDistrictToCitizen")]
    partial class AddDistrictToCitizen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartComplaint.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Road Repair",
                            DepartmentId = 1,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Street Lighting",
                            DepartmentId = 1,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Cleanliness",
                            DepartmentId = 2,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Waste Collection",
                            DepartmentId = 2,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Water Leakage",
                            DepartmentId = 3,
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "No Water Supply",
                            DepartmentId = 3,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Citizen", b =>
                {
                    b.Property<string>("CitizenId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CitizenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            CitizenId = "CITTA001",
                            Address = "12, Gandhi Street, Chennai",
                            District = "Chennai",
                            Email = "anu@gmail.com",
                            IsActive = true,
                            Name = "Anu Priya",
                            Phone = "9876543210",
                            State = "Tamil Nadu",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OfficerImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OfficerRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ComplaintId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StatusId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            ComplaintId = 1,
                            CategoryId = 2,
                            CitizenId = "CITTA001",
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Description = "Street light near my house is not working for over a week.",
                            IsActive = true,
                            Location = "Anna Nagar, Chennai",
                            StatusId = 1,
                            Title = "Broken Street Light"
                        },
                        new
                        {
                            ComplaintId = 2,
                            CategoryId = 4,
                            CitizenId = "CITTA001",
                            CreatedAt = new DateTime(2025, 1, 2, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Description = "Garbage has not been collected in our area for 3 days.",
                            IsActive = true,
                            Location = "T Nagar, Chennai",
                            StatusId = 2,
                            Title = "Garbage Not Collected"
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.ComplaintAssignment", b =>
                {
                    b.Property<string>("OfficerId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("OfficerId", "ComplaintId");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintAssignments");

                    b.HasData(
                        new
                        {
                            OfficerId = "OFFFO001",
                            ComplaintId = 1,
                            AssignedDate = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Remarks = "Assigned for field inspection"
                        },
                        new
                        {
                            OfficerId = "OFFFO001",
                            ComplaintId = 2,
                            AssignedDate = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Remarks = "Pending assignment approval"
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Public Works",
                            Description = "Handles infrastructure and road-related issues.",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Sanitation",
                            Description = "Manages cleanliness, waste, and hygiene concerns.",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Water Supply",
                            Description = "Resolves water supply and leakage complaints.",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Grievance", b =>
                {
                    b.Property<int>("GrievanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrievanceId"));

                    b.Property<string>("AssignedOfficerId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OfficerImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OfficerRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginalOfficerId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("RaisedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Response")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("GrievanceId");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("OriginalOfficerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Grievances");

                    b.HasData(
                        new
                        {
                            GrievanceId = 1,
                            CitizenId = "CITTA001",
                            ComplaintId = 1,
                            Description = "Complaint not resolved within promised timeframe",
                            IsActive = true,
                            OriginalOfficerId = "OFFFO001",
                            RaisedDate = new DateTime(2025, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("CitizenId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrievanceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OfficerId")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("NotificationId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("GrievanceId");

                    b.HasIndex("OfficerId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            ComplaintId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsRead = false,
                            Message = "New complaint assigned: Broken Street Light",
                            OfficerId = "OFFFO001"
                        },
                        new
                        {
                            NotificationId = 2,
                            CreatedAt = new DateTime(2025, 1, 5, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            GrievanceId = 1,
                            IsActive = true,
                            IsRead = false,
                            Message = "Grievance raised for complaint: Broken Street Light",
                            OfficerId = "OFFFO001"
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Officer", b =>
                {
                    b.Property<string>("OfficerId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProofDocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OfficerId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Officers");

                    b.HasData(
                        new
                        {
                            OfficerId = "OFFFO001",
                            DepartmentId = 1,
                            Email = "raj@gmail.com",
                            IsActive = true,
                            IsApproved = false,
                            Name = "Raj Kumar",
                            Role = 1,
                            State = "Tamil Nadu",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            IsActive = true,
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            IsActive = true,
                            StatusName = "InProgress"
                        },
                        new
                        {
                            StatusId = 3,
                            IsActive = true,
                            StatusName = "Resolved"
                        },
                        new
                        {
                            StatusId = 4,
                            IsActive = true,
                            StatusName = "Closed"
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@gmail.com",
                            IsActive = true,
                            Password = "Admin@123",
                            Role = 3,
                            Username = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "raj@gmail.com",
                            IsActive = true,
                            Password = "Officer@123",
                            Role = 2,
                            Username = "Raj Kumar"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "anu@gmail.com",
                            IsActive = true,
                            Password = "Citizen@123",
                            Role = 1,
                            Username = "Anu Priya"
                        });
                });

            modelBuilder.Entity("SmartComplaint.Models.Category", b =>
                {
                    b.HasOne("SmartComplaint.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SmartComplaint.Models.Citizen", b =>
                {
                    b.HasOne("SmartComplaint.Models.User", "User")
                        .WithOne("Citizen")
                        .HasForeignKey("SmartComplaint.Models.Citizen", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartComplaint.Models.Complaint", b =>
                {
                    b.HasOne("SmartComplaint.Models.Category", "Category")
                        .WithMany("Complaints")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartComplaint.Models.Citizen", "Citizen")
                        .WithMany("Complaints")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartComplaint.Models.Department", "Department")
                        .WithMany("Complaints")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartComplaint.Models.Status", "Status")
                        .WithMany("Complaints")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Citizen");

                    b.Navigation("Department");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SmartComplaint.Models.ComplaintAssignment", b =>
                {
                    b.HasOne("SmartComplaint.Models.Complaint", "Complaint")
                        .WithMany("ComplaintAssignments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartComplaint.Models.Officer", "Officer")
                        .WithMany("ComplaintAssignments")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complaint");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("SmartComplaint.Models.Grievance", b =>
                {
                    b.HasOne("SmartComplaint.Models.Officer", "AssignedOfficer")
                        .WithMany("AssignedGrievances")
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartComplaint.Models.Citizen", "Citizen")
                        .WithMany("Grievances")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartComplaint.Models.Complaint", "Complaint")
                        .WithMany("Grievances")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartComplaint.Models.Officer", "OriginalOfficer")
                        .WithMany("OriginalGrievances")
                        .HasForeignKey("OriginalOfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartComplaint.Models.Status", "Status")
                        .WithMany("Grievances")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Citizen");

                    b.Navigation("Complaint");

                    b.Navigation("OriginalOfficer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SmartComplaint.Models.Notification", b =>
                {
                    b.HasOne("SmartComplaint.Models.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId");

                    b.HasOne("SmartComplaint.Models.Complaint", "Complaint")
                        .WithMany("Notifications")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartComplaint.Models.Grievance", "Grievance")
                        .WithMany("Notifications")
                        .HasForeignKey("GrievanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartComplaint.Models.Officer", "Officer")
                        .WithMany("Notifications")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Citizen");

                    b.Navigation("Complaint");

                    b.Navigation("Grievance");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("SmartComplaint.Models.Officer", b =>
                {
                    b.HasOne("SmartComplaint.Models.Department", "Department")
                        .WithMany("Officers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartComplaint.Models.User", "User")
                        .WithOne("Officer")
                        .HasForeignKey("SmartComplaint.Models.Officer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartComplaint.Models.Category", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("SmartComplaint.Models.Citizen", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Grievances");
                });

            modelBuilder.Entity("SmartComplaint.Models.Complaint", b =>
                {
                    b.Navigation("ComplaintAssignments");

                    b.Navigation("Grievances");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SmartComplaint.Models.Department", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Officers");
                });

            modelBuilder.Entity("SmartComplaint.Models.Grievance", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SmartComplaint.Models.Officer", b =>
                {
                    b.Navigation("AssignedGrievances");

                    b.Navigation("ComplaintAssignments");

                    b.Navigation("Notifications");

                    b.Navigation("OriginalGrievances");
                });

            modelBuilder.Entity("SmartComplaint.Models.Status", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Grievances");
                });

            modelBuilder.Entity("SmartComplaint.Models.User", b =>
                {
                    b.Navigation("Citizen")
                        .IsRequired();

                    b.Navigation("Officer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
